# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
workflows:
  version: 2

  deploy-publish:
    jobs:
      deploy:
        branches:
          only:
            - master
        docker:
          # specify the version you desire here
          - image: circleci/node:11.6.0
            environment:
              PRISMA_MARVEL_PRIVATE_KEY: 140a52c97a8ef92f028d89a543e83d711f9e80a0
              PRISMA_MARVEL_API_KEY: ba0613cb148841f5091cb0075b5076d2
              PRISMA_ENDPOINT: https://us1.prisma.sh/raj-singh/marvel-api/production
              PRISMA_SECRET: mysecret123
          # Specify service dependencies here if necessary
          # CircleCI maintains a library of pre-built images
          # documented at https://circleci.com/docs/2.0/circleci-images/
          # - image: circleci/mongo:3.4.4

        working_directory: ~/repo

        steps:
          - checkout

          # Download and cache dependencies
          - restore_cache:
              keys:
                - v1-dependencies-{{ checksum "package.json" }}
                # fallback to using the latest cache if no exact match is found
                - v1-dependencies-

          - run: yarn install

          - save_cache:
              paths:
                - node_modules
              key: v1-dependencies-{{ checksum "package.json" }}

          # run tests!
          - run: yarn deploy
      publish-apollo:
        requires:
          - deploy
        branches:
          only:
            - master
        docker:
          # specify the version you desire here
          - image: circleci/node:11.6.0
        working_directory: ~/repo
        steps:
          # Download and cache dependencies
          - restore_cache:
              keys:
                - v1-dependencies-2.3.1
                # fallback to using the latest cache if no exact match is found
                - v1-dependencies-

          - run: yarn global add apollo@2.3.1

          - save_cache:
              paths:
                - node_modules
              key: v1-dependencies-2.3.1

          # run tests!
          - run: yarn apollo:publish
